app = "crypto-ema-telegram-bot"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    port = 8080
    handlers = ["http"]

  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50
