app = "crypto-ema-telegram-bot"

[build]
  image = "registry.fly.io/crypto-ema-telegram-bot"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
